name : build and deploy with ssh & rsync
on : 
  push:
   branches: [main]
  pull_request:
   branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkoutcode
      uses: actions/checkout@v2
    - name: rsync
      uses: burnett01/rsync-deployments@5.2
      with:
       switches: -avzr --delete --exclude="exclude_this" --include="" --filter=""
       remote_host: ${{secrets.HOST}}
       remote_user: ${{secrets.USER}}
       remote_password: ${{secrets.PASS}}
       path: "*"
       remote_path: "~/my-project"
       remote_key_pass: ${{secrets.KEY}}
#        runBeforeDeployment: |
#         cd somewhere/
       runAfterDeployment: |
        echo "first line" >> echofile1.txt
        echo "second line" >> echofile2.txt
