name : build and deploy with ssh & rsync
on : 
  push:
   branches: [main]
  pull_request:
   branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkoutcode
      uses: actions/checkout@v2
    - name: rsync
      uses: burnett01/rsync-deployments@5.2
      with:
       switches: -avzr --delete --exclude="" --include="" --filter=""
       remote_host: ${{secrets.HOST}}
       remote_user: ${{secrets.USER}}
       path: "*"
       remote_path: "~/my-project"
       remote_key: ${{secrets.KEY}}
    - name: sshaftercheckout
      uses: tarunjangra/ssh-remote-cmd@v1
      with:
       command:
         echo "i edited this btw" > echofile.txt
         echo "i edited this too" > echofile2.txt
       host: ${{secrets.HOST}}
       user: ${{secrets.USER}}
       key: ${{secrets.KEY}}
#        runBeforeDeployment: |
#         cd somewhere/
